name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - name: Build Docker image
        run: docker build -t my-app .

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - name: Tests
        run: |
          echo "Running tests..."
          go test -v ./tests/...
          echo "Tests passed!"

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Test Server
        run: |
          echo "Deploying to server..."
          sleep 10
          docker ps
          echo "Deployment to test server complete!"
          
